openapi: 3.0.3
info:
  title: BetGames
  version: '1.0'
  x-logo:
    url: ''
  description: This is the api documentation of BetGames
paths:
  /user/login:
    summary: Login the user
    description:
      This path is used to log the user if the credentials are good, return an
      error if the credentials are wrong
    post:
      operationId: login
      summary: Login the user
      description: This operation is used to login the user
      parameters:
        - name: mail
          in: query
          description: The mail of the user used to login
          required: true
          deprecated: false
          example: '"qwer.tyu@toto.com"'
          schema:
            type: string
            format: email
          allowEmptyValue: false
          x-last-modified: 1665868792586
        - name: password
          in: query
          description: The password of the user
          required: true
          deprecated: false
          example: '"123456qwerty!@#"'
          schema:
            type: string
            format: password
          allowEmptyValue: false
          x-last-modified: 1665868671171
      responses:
        400:
          description: The email or the password are wrong
          x-last-modified: 1665869428764
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: '"Wrong email or password"'
                    x-last-modified: 1665869428764
              examples: {}
              encoding: {}
        200:
          description: The user is connected
          x-last-modified: 1665869013995
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: '"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZjM0ZjQ2ODU1MzU4MDAxM2Q0NzQwZCIsImlhdCI6MTY2NTg2NjIyOCwiZXhwIjoxNjY1OTUyNjI4fQ.8Y0YV7mYKjZc3qZ3jK6W1C5O5x2b3qo3c"'
              examples: {}
              encoding: {}
    delete:
      operationId: logout
      responses:
        200:
          description: The user is disconnected
          x-last-modified: 1665869013995
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: '"User disconnected"'
              examples: {}
              encoding: {}
    x-last-modified: 1665867774437

servers:
  - url: https://Betgamesback-env.eba-wneafxtm.us-east-1.elasticbeanstalk.com
    description: The AWS where the back is autodeploy at each commit
    variables: {}
    x-last-modified: 1665867471272
security: []
